# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install --global dotnet-sonarscanner
      dotnet-sonarscanner begin /k:"SecureGovernment_Scanner" /o:"securegovernment" /d:sonar.login="$(sonar-login)"
      dotnet build src/SecureGovernment.sln --configuration $(buildConfiguration)
      dotnet test src/SecureGovernment.Domain.Tests/SecureGovernment.Domain.Tests.csproj --configuration $(buildConfiguration)
      dotnet-sonarscanner end /d:sonar.login="$(sonar-login)
    noProfile: false
    noRc: false
  displayName: 'Running build script'

